### ISSUE TITLE
Nenaudoti curl tiesogiai

### ISSUE THREAD

**Issue by ellisv** [kaDDDar/Library#2]
Vietoje curl siūlau naudoti [Buzz](https://github.com/kriswallsmith/Buzz), yra ir oficialus bundle - [SensioBuzzBundle](https://github.com/sensiolabs/SensioBuzzBundle)

**Comment by kaDDDar** [comment]
Pakeiciau is curl i Buzz

**Comment by ellisv** [comment]
Matau. Bet užuot konstruojant naują objketą ten jį turėtum injectinti.

**Comment by kaDDDar** [comment]
Ahh... tiesa, tas senas blogas copy/paste :) O kaip man injektinti Buzz? jis nėra užregistruotas kaip service'as, bent jau aš negaliu jo surasti per "app/console container:debug"?

**Comment by kaDDDar** [comment]
Uzregistravau buzz kaip service'a ir injectinau, nezinau ar taip gerai, butu gerai kad pakomentuotum. Aciu.

**Comment by kaDDDar** [comment]
Panaudojau SensioBuzzBundle vietoj tieisoginio Buzz
