### ISSUE TITLE
Ištrinti nereikalingus failus ir funkcionalumus iš WeatherBundle

### ISSUE THREAD

**Issue by ellisv** [kaDDDar/Library#3]
- WeatherBundle turėtų turėti logiką susijusiu tik su orų gavimu ir atidavimu
- Nereikia ten turėti jokių Controllers, Views, Translations ar Router'io konfiguraciją
- Kolkas DependencyInjection\Configuration.php irgi nenaudojamas

**Comment by kaDDDar** [comment]
Pravaliau projekta nuo nereikalingu funkcionalumu
