### ISSUE TITLE
Object\Location →Struct\Location

### ISSUE THREAD

**Issue by ellisv** [kaDDDar/Library#4]
Object realiai nieko nepasako ir yra visiškai nereikšmingas. Jei nori Location klasę turėti atskiroje direktorijoje, tai galbūt ją geriau būtų pervadinti į Struct.

**Comment by kaDDDar** [comment]
Aš nelabai žinojau kur šią klasę padėti... niekur nelipo, tai idėjau i object. Dabar pakeičiau į Struct.
